apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: soufian1/chat-app-frontend:sha-5db1212df56168b3c0e193d02485110663044ddc
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: VITE_API_URL
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
