apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: chat-app
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
  namespace: chat-app
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
  selector:
    app: gateway
