apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: chat-app
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      containers:
        - name: ollama
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
