apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: chat-app
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
