apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: chat-app
  labels:
    app: ollama
spec:
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  selector:
    app: ollama
