apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: chat-app
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: soufian1/chat-app-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-app-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chat-app-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: chat-app-secrets
                  key: REDIS_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: chat-app-secrets
                  key: RABBITMQ_URL
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: JWT_ALGORITHM
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: CORS_ORIGINS
            - name: ENABLE_DEMO_WORKER
              valueFrom:
                configMapKeyRef:
                  name: chat-app-config
                  key: ENABLE_DEMO_WORKER
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
