apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: chat-app
  labels:
    app: gateway
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: gateway
