apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres/configmap-init.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - redis/service.yaml
  - redis/deployment.yaml
  - rabbitmq/service.yaml
  - rabbitmq/deployment.yaml
  - ollama/service.yaml
  - ollama/pvc.yaml
  - ollama/deployment.yaml
  - gateway/service.yaml
  - gateway/deployment.yaml
  - worker/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress/ingress.yaml
  - ingress/nodeport.yaml

commonLabels:
  app.kubernetes.io/part-of: chat-app
  app.kubernetes.io/managed-by: kustomize
