apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/ollama-gpu.yaml
  - path: patches/images.yaml
  - path: patches/secrets.yaml

configMapGenerator:
  - name: chat-app-config
    behavior: merge
    literals:
      - VITE_API_URL=/api
